# Generated by Django 4.2.6 on 2023-10-10 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='priec',
            new_name='price',
        ),
    ]
